# Сервис JSON-B

# Секрет - коннектор к базе данных
apiVersion: v1
kind: Secret
metadata:
  name: jsonb-secrets
type: Opaque
data:
  psql_connect: cG9zdGdyZXNxbDovL19fdGVzdF9hcHBfY29yZTpfX3Rlc3RfYXBwX2NvcmVAMTAuOTcuMTgzLjMyOjU0MzIvX190ZXN0X2FwcF9jb3Jl
---

# Требование волюма PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jsonb-claim-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---

# Деплой
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonb-service
  labels:
    mentor: IvanKozlov
    contact_telegram: "89004930206"
    app: jsonb-service
    function: metadata-storage

spec:
  selector:
    matchLabels:
      app: jsonb-service-label
  template:
    metadata:
      labels:
        app: jsonb-service-label
    spec:
      containers:
      - name: jsonb-service-container
        image: atom1994/jsonb_service
        ports:
        - containerPort: 5112
        env:
        - name: ITS_DOCKER
          value: "True"
        - name: PYTHONPATH
          value: "/jsonb_service"
        - name: DATABASE_SETTINGS_URL_DOCKER
          valueFrom:
            secretKeyRef:
              name: jsonb-secrets
              key: psql_connect

        volumeMounts:
          - name: jsonb-data
            mountPath: /jsonb_service/__migrations/

      volumes:
        - name: jsonb-data
          persistentVolumeClaim:
            claimName: jsonb-claim-data


---

# Сервис
apiVersion: v1
kind: Service
metadata:
  name: jsonb-service
  labels:
    mentor: IvanKozlov
    contact_telegram: "89004930206"
    app: jsonb-service
    function: metadata-storage
spec:
  type: LoadBalancer
  selector:
    app: jsonb-service-label
  ports:
    - name: "5112"
      protocol: TCP
      port: 5112
      targetPort: 5112


---

# Автоскелер

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: jsonb-service-autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: jsonb-service
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80