version: '3'


#Внешние волюмы
volumes:
    psql_sub_module_storage_atlant:
        external: true



# Общая сеть между разными микросервисами (композами)
networks:
  default:
   external:
    name: general_network_all_services


# Сервисы
services:


  # Постгрес (официальная сборка)
  sub_module_storage_atlant_postgres:
    restart: always
    image: postgres:13
    container_name: sub_module_storage_atlant_postgres
    command: postgres -c 'max_connections=5000'
    ports:
      - 5432:5432
    volumes:
      - psql_sub_module_storage_atlant:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: __test_app_core
      POSTGRES_USER: __test_app_core
      POSTGRES_DB: __test_app_core

    # внешняя сеть




  # Кликхаус (официальная сборка)
  sub_module_storage_atlant_clickhouse:
    image: yandex/clickhouse-server
    container_name: sub_module_storage_atlant_clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./__docker/volumes/clickhouse/cl_db:/var/lib/clickhouse


    # внешняя сеть


    restart: on-failure





  #  Контроллер кластера - зоопарк менеджер - зукипер
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    container_name: zookeeper
    restart: on-failure

    ports:
      - 2181:2181

    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888

    volumes:
      - ./__docker/volumes/kafka/zoo/data:/data
      - ./__docker/volumes/kafka/zoo/log:/datalog


    # внешняя сеть



  # Первый брокер - полноценный контейнер кафки порт 9091

  kafka1:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka1
    container_name: kafka1
    restart: on-failure

    ports:
      - 9091:9091

    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - ./__docker/volumes/kafka/k1:/var/lib/kafka/data


    # внешняя сеть


    depends_on:
      - zookeeper

  # Второй брокер - полноценный контейнер кафки порт 9092

  kafka2:

    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka2
    container_name: kafka2
    restart: on-failure

    ports:
      - 9092:9092

    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - ./__docker/volumes/kafka/k2:/var/lib/kafka/data


    # внешняя сеть


    depends_on:
      - zookeeper


  # Третий брокер - полноценный контейнер кафки порт 9093

  kafka3:

    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka3
    container_name: kafka3
    restart: on-failure

    ports:
      - 9093:9093

    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - ./__docker/volumes/kafka/k3:/var/lib/kafka/data


    # внешняя сеть


    depends_on:
      - zookeeper

  # Админское GUI

  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop
    container_name: kafdrop
    restart: on-failure
    ports:
      - 9001:9001

    environment:
      KAFKA_BROKERCONNECT: "kafka1:19091"
      SERVER_PORT: 9001


    # внешняя сеть


    depends_on:
      - kafka1
      - kafka2
      - kafka3


  #  Сервис-хранилище метаданных JSON-B
  jsonb_service:
    image: atom1994/jsonb_service
    restart: on-failure
    container_name: jsonb_service

    ports:
      - 5112:5112

    volumes:

     - ./__jsonb_docker_migrations:/jsonb_service/__migrations/

    env_file:
      - .env.jsonb

    environment:
      ITS_DOCKER: "True"

    depends_on:
     - sub_module_storage_atlant_postgres


  # Ядро
  sub_module_storage_atlant:
    image: atom1994/storage_atlant
    restart: on-failure
    container_name: sub_module_storage_atlant


    ports:
      - 5111:5111


    volumes:

     - ./__migrations:/__sub_module_storage_atlant/__migrations/

     - ./NSI:/__sub_module_storage_atlant/__fast_api_app/models/general/NSI/

     - ./data_launch_system:/__sub_module_storage_atlant/data_launch_system/

     - ./__test_data:/__sub_module_storage_atlant/__test_data/


    env_file:
      - .env.storage

    environment:
      ITS_DOCKER: "True"

    depends_on:

     - sub_module_storage_atlant_postgres


     - sub_module_storage_atlant_clickhouse


     - kafdrop
     - jsonb_service



