version: '3'

# Подводные камни винды... Предварительно создать: docker volume create
volumes:
  postgres_ex:
    external: true

# Общая сеть между микросервисами
networks:
  webappnetwork:
    driver: bridge

# Сервисы
services:

  # Постгрес (официальная сборка). Настройки
  postgres_settings:
    image: postgres
    container_name: postgres_settings
    command: postgres -c 'max_connections=2000'
    ports:
      - 5432:5432
    volumes:
      - postgres_ex:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: __test_app_core
      POSTGRES_USER: __test_app_core
      POSTGRES_DB: __test_app_core

    networks:
      - webappnetwork

    restart: on-failure
