from .models import ORM_nsi_farmerpassport_source_systems
from tortoise.contrib.pydantic import pydantic_model_creator
PYD_nsi_farmerpassport_source_systems = pydantic_model_creator(ORM_nsi_farmerpassport_source_systems)