version: '3'



# Общая сеть между разными микросервисами (композами)
networks:
  default:
   external:
    name: general_network_all_services


# Сервисы
services:

#  Сервис-хранилище метаданных JSON-B
  jsonb_service:
    image: atom1994/jsonb_service
    restart: on-failure
    container_name: jsonb_service

    volumes:

     - ./__jsonb_docker_migrations:/jsonb_service/__migrations

    env_file:
      - .env.jsonb

    environment:
      ITS_DOCKER: "True"

    network_mode: host


  # Ядро
  farmer_passport:
    image: atom1994/storage_atlant
    restart: on-failure
    container_name: storage_atlant

    volumes:
    
     - ./__migrations:/__sub_module_storage_atlant/__migrations/
     - ./data_launch_system:/__sub_module_storage_atlant/data_launch_system/
     - ./NSI:/__sub_module_storage_atlant/__fast_api_app/models/general/NSI/
     - ./__test_data:/__sub_module_storage_atlant/__test_data/


    env_file:
      - .env.development

    environment:
      ITS_DOCKER: "True"

    depends_on:

     - jsonb_service
     
    network_mode: host



