from .models import ORM_nsi_farmerpassport_economic_indicators
from tortoise.contrib.pydantic import pydantic_model_creator
PYD_nsi_farmerpassport_economic_indicators = pydantic_model_creator(ORM_nsi_farmerpassport_economic_indicators)