from .models import ORM_nsi_farmerpassport_organizations
from tortoise.contrib.pydantic import pydantic_model_creator
PYD_nsi_farmerpassport_organizations = pydantic_model_creator(ORM_nsi_farmerpassport_organizations)